-- PRACTICE SQL 4: 

-- Q1: WRITE A QUERY THAT DISPLAYS THE NUMBER OF CUSTOMERS THAT HAVE A BALANCE OF $0.00.

SELECT COUNT(*) AS CUS_NUMER FROM CUSTOMER WHERE CUS_BALANCE = 0;

-- Q2: WRITE A QUERY THAT DISPLAYS THE LARGEST CUSTOMER BALANCE AND THE AVERAGE CUSTOMER BALANCE.

SELECT FORMAT(MAX(CUS_BALANCE),'C') AS LARGEST_CUS_BALANCE, FORMAT(AVG(CUS_BALANCE), 'C') AS AVG_BALANCE FROM CUSTOMER;

-- Q3: WRITE A QUERY TO DISPLAY HOW MANY DIFFERENT CUSTOMERS HAVE PLACED AN ORDER.

SELECT COUNT(DISTINCT CUS_CODE ) AS "CUSOTMER NUMBER" FROM INVOICE;

-- Q4: WRITE A QUERY THAT DISPLAYS THE CUSTOMER CODE AND THE LAST NAME, AND THE NUMBER OF ORDERS THAT THE CUSTOMER HAS PLACED, FOR CUSTOMERS
-- THAT HAVE PLACED ATLEAST ONE ORDER. SORT THE RESULT BY CUSTOMER CODE.

SELECT I.CUS_CODE ,CUS_LNAME AS "CUSTOMER NAME", COUNT(INV_NUMBER) AS "NUMBER OF ORDERS" FROM INVOICE I JOIN CUSTOMER C ON I.CUS_CODE = C.CUS_CODE 
GROUP BY I.CUS_CODE , CUS_LNAME ORDER BY CUS_CODE;

-- Q5: WRITE A QUERY TO DISPLAY THE CUSTOMER CODE AND THE LAST NAME AND THE NUMBER OF ORDERS THAT THE CUSTOMER HAS PLACED 
-- AND THE CUSTOMER BALANCE. SORT THE RESULT BY CUSTOMER CODE.

SELECT C.CUS_CODE, CUS_LNAME,COUNT(INV_NUMBER) AS "NUMBER OF ORDERS" , CUS_BALANCE FROM CUSTOMER C JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
GROUP BY C.CUS_CODE,CUS_LNAME,CUS_BALANCE 
ORDER BY C.CUS_CODE;

-- 














